### PR TITLE
fix(ci): install libsasl2-dev so --all-features clippy stops killing every Release run

### PR DESCRIPTION
**Pull request by Knucklessg1**
Proof-run PR for CX lane WD10-P-EGCI. The only signal being read here is the `Lint + architecture gates` job, which failed on every push to main from 2026-08-18 through run 33200059527 with sasl2-sys-0.1.22+2.1.28/build.rs:343 "Unable to find libsasl2 on your system" (exit 101). Vendoring was measured and rejected — see the commit body.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

https://claude.ai/code/session_012CTXVNPprCqqvS5uQFNcVD

### CODE REVIEW

**Comment by Knucklessg1** [comment]
Lane WD10-P-EGCI status — **this PR is a CI proof, not a complete fix.**

Run 33206072439: `Clippy (every crate, all features)` **PASSES** (18m15s) for the first time since `cdc-kafka` landed; `Clippy (slim lib)` passes; the job then fails at `Clippy (slim server)` on **7 pre-existing compile errors on main** that this branch does not touch and does not own:

- `src/server/dispatch.rs:3290,3313,3451` — `cannot find trait PersistenceBackend` (introduced by d3736262)
- `src/server/handlers/graph_ops.rs:371,383,390` — `cannot find reasoning in crate` (introduced by bd327b7e)
- `src/server/mutation_batch.rs:256` — `cannot find redb_store in crate` (82d0a740)

Reproduced locally on Linux: `cargo check --no-default-features --features server` → same 7 errors, exit 101. Full analysis in `plans/complex/lane-reports/WD10-P-EGCI.md`.
